apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.ip }}
  ports:
  - name: rtmp
    protocol: TCP
    port: {{ .Values.service.rtmpPort }}
    targetPort: {{ .Values.service.rtmpPort }}
  - name: proxy
    protocol: TCP
    port: {{ .Values.service.proxyPort }}
    targetPort: {{ .Values.service.proxyPort }}
  - name: ingest
    protocol: TCP
    port: {{ .Values.service.ingestPort }}
    targetPort: {{ .Values.service.ingestPort }}
  selector:
    app: {{ .Chart.Name }}
