apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicasCount | default  "1" }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailableCount }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.http.port }}
            - containerPort: {{ .Values.service.rtmp.port }}
          volumeMounts:
            - mountPath: /data/studio
              name: {{ .Chart.Name }}-{{ .Values.config.env }}-fs
            - mountPath: /opt/stream-ingester/etc/stream-ingester-rtmp.conf
              name: config
              subPath: rtmpConf
        - name: {{ .Release.Name }}-hookd
          image: "{{ .Values.hookd.image.repository }}:{{ .Values.hookd.image.tag }}"
          imagePullPolicy: {{ .Values.hookd.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.hookd.service.http.port }}
          volumeMounts:
            - mountPath: /data/studio
              name: {{ .Chart.Name }}-{{ .Values.config.env }}-fs
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: STREAMS_RPC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: streamsRpcAddr
            - name: DISPATCHER_RPC_ADDR
              valueFrom:
                configMapKeyRef:
                  name: {{ .Chart.Name }}
                  key: dispatcherRpcAddr
            - name: VC_HOOKD_HLSDIR
              value: /data/studio/hls
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: sentryDsn
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: secrets
          secret:
            secretName: {{ .Release.Name }}
        - name: {{ .Chart.Name }}-{{ .Values.config.env }}-fs
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-{{ .Values.config.env }}-fs
            readOnly: false
      nodeSelector:
        cloud.google.com/gke-nodepool: ingester
