apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicasCount | default  "1" }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailableCount }}
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      automountServiceAccountToken: true
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.ports.http }}
            - containerPort: {{ .Values.service.ports.rtmp }}
          volumeMounts:
            - mountPath: /data/studio
              name: {{ .Chart.Name }}-fs
            - mountPath: /opt/stream-ingester/etc/stream-ingester-rtmp.conf
              name: config
              subPath: rtmpConf
        - name: {{ .Release.Name }}-hookd
          image: "{{ .Values.hookd.image.repository }}:{{ .Values.hookd.image.tag }}"
          imagePullPolicy: {{ .Values.hookd.image.pullPolicy }}
          command: ["bash", "-c", "source /vault/secrets/common && source /vault/secrets/config && /hookd"]
          ports:
            - containerPort: {{ .Values.hookd.service.ports.http }}
          volumeMounts:
            - mountPath: /data/studio
              name: {{ .Chart.Name }}-fs
          env:
            - name: JAEGER_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: JAEGER_AGENT_PORT
              value: "6831"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
        - name: config-env
          configMap:
            name: {{ .Release.Name }}-env
        - name: {{ .Chart.Name }}-fs
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-fs
            readOnly: false
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
