apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.http.type }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.http.port }}
    targetPort: {{ .Values.service.http.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rtmp
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
  - name: rtmp
    protocol: TCP
    port: {{ .Values.service.rtmp.port }}
    targetPort: {{ .Values.service.rtmp.port }}
