apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.ports.http }}
    targetPort: {{ .Values.service.ports.http }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rtmp
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
  - name: rtmp
    protocol: TCP
    port: {{ .Values.service.ports.rtmp }}
    targetPort: {{ .Values.service.ports.rtmp }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-lb
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  sessionAffinity: ClientIP
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: rtmp
    protocol: TCP
    port: {{ .Values.service.ports.rtmp }}
    targetPort: {{ .Values.service.ports.rtmp }}
  - name: http
    protocol: TCP
    port: {{ .Values.service.ports.http }}
    targetPort: {{ .Values.service.ports.http }}
