image:
  repository: us.gcr.io/videocoin-network/ingester
  tag: latest
  pullPolicy: Always

config:
  minReplicas: "1"
  maxReplicas: "5"

service:
  rtmp:
    type:
    port: 1935
  http:
    type:
    port: 80

resources: {}
