image:
  repository: us.gcr.io/videocoin-network/ingester
  tag: latest
  pullPolicy: Always

replicasCount: 3

service:
  rtmp:
    type:
    port: 1935
  http:
    type:
    port: 80

resources: {}

hookd:
  image:
    repository: us.gcr.io/videocoin-network/ingester-hookd
    tag: latest
    pullPolicy: Always
  service:
    http:
      type:
      port: 8887
