apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    component: rtmp-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        component: rtmp-server
    spec:
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: {{ .Values.service.internalPort }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: LP_CAMERA_HTTPADDR
              value: cameras-api
            - name: LP_MANAGER_ADDR
              value: manager-api-proxy
            - name: LP_VIDEOUPLOADER_ADDR
              value: video-uploader-api
            - name: LP_STREAMINGESTER_PORT
              value: "{{ .Values.service.internalPort }}"
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/stream-ingester/etc
        - name: dnsmasq
          image: "janeczku/go-dnsmasq:release-1.0.5"
          args:
            - --listen
            - "127.0.0.1:53"
            - --default-resolver
            - --append-search-domains
            - --hostsfile=/etc/hosts
            - --verbose
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Name }}
            items:
            - key: nginx.conf
              path: nginx.conf
            - key: base.conf
              path: includes/base.conf
            - key: env.conf
              path: includes/env.conf
            - key: rtmp.conf
              path: includes/rtmp.conf
            - key: http.conf
              path: includes/http.conf 
            - key: metrics.conf
              path: includes/metrics.conf
            - key: storage.conf
              path: includes/storage.conf
            - key: hook.conf
              path: includes/hook.conf
            - key: cameras_api.conf
              path: includes/cameras_api.conf
            - key: videouploader_api.conf
              path: includes/videouploader_api.conf
            - key: private_api.conf
              path: includes/private_api.conf
            - key: resolver.conf
              path: includes/resolver.conf
            - key: init_lua.conf
              path: includes/init_lua.conf
            - key: cors.conf
              path: includes/cors.conf