apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.ingress.staticIpName }}"
spec:
  backend:
    serviceName: {{ .Chart.Name }}
    servicePort: {{ .Values.service.name }}
  rules:
    - host: {{ .Values.ingress.httpHost }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Chart.Name }}
            servicePort: {{ .Values.service.name }}
  tls:
    - secretName: {{ .Chart.Name }}-ingress-tls
      hosts:
        - {{ .Values.ingress.httpHost }}
