apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    component: rtmp-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ .Chart.Name }}
    component: rtmp-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rtmp
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Name }}-rtmp
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: rtmp-server
  type: LoadBalancer
  ports:
    - port: {{ .Values.rtmpService.externalPort }}
      targetPort: {{ .Values.rtmpService.internalPort }}
      protocol: TCP
      name: {{ .Values.rtmpService.name }}
  loadBalancerIP: {{ .Values.rtmpService.loadBalancerIP }}