replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/ingester
  tag: latest
  pullPolicy: Always

service:
  rtmp:
    type:
    port: 1935
  http:
    type:
    port: 80

resources: {}

hookd:
  image:
    repository: gcr.io/videocoin-network/ingester-hookd
    tag: latest
    pullPolicy: Always
  service:
    http:
      type:
      port: 8887

config:
  fsPath:
  fsAddr:
