replicasCount: 1
maxUnavailableCount: 0

image:
  repository: registry.videocoin.net/cloud/ingester
  tag: latest
  pullPolicy: Always
  pullSecrets: 
  - name: regcred

service:
  loadBalancerIP: "146.148.85.25"
  ports:
    rtmp: 1935
    http: 80

hookd:
  image:
    repository: registry.videocoin.net/cloud/ingester-hookd
    tag: latest
    pullPolicy: Always
    pullSecrets: 
    - name: regcred
  service:
    ports:
      http: 8887

serviceAccount:
  name: default

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 1000m
    memory: 1024Mi

autoscaler:
  minCount: 1
  maxCount: 3
  targets:
    targetCPUUtilizationPercentage: 70

configEnv:
  VC_HOOKD_HLSDIR: "/data/studio/hls"
  DISPATCHER_RPC_ADDR: "dispatcher.console.svc.cluster.local:5008" 
  STREAMS_RPC_ADDR: "streams.console.svc.cluster.local:5102"

config:
  httpConf: |
    user www-data;

    worker_processes 4;

    events {
        worker_connections 1024;
    }

    http {
        resolver 127.0.0.1:53 valid=10s ipv6=off;
        resolver_timeout 5s;

        error_log /var/log/stream-ingester/http.error.log warn;
        access_log /var/log/stream-ingester/http.access.log combined;

        server {
            listen *:80;
            server_name localhost;

            listen 443 ssl default_server;
            listen [::]:443 ssl default_server;
            include includes/ssl.conf;
            include includes/ssl-params.conf;

            location ~ /.well-known {
                    allow all;
            }

            include includes/storage.conf;
        }
    }
  rtmpConf: |
    user www-data;

    worker_processes 1;

    events {
        worker_connections 1024;
    }

    rtmp {
        server {
            listen 1935;

            chunk_size 4096;
            max_message 16M;

            application live {
                live on;
                meta copy;

                drop_idle_publisher 10s;

                record_path /data/studio/records;
                record_unique on;

                notify_method         post;
                notify_update_timeout 5s;
                notify_update_strict  on;
                notify_send_redirect  on;
                notify_relay_redirect on;

                on_publish       http://127.0.0.1:8887/hook;
                on_publish_done  http://127.0.0.1:8887/hook;
                on_playlist      http://127.0.0.1:8887/hook;
                on_update        http://127.0.0.1:8887/hook;

                hls on;
                hls_type live;
                hls_fragment 10s;
                hls_playlist_length 43200s;

                hls_fragment_slicing plain;
                hls_path /data/studio/hls;
                hls_cleanup on;
                hls_continuous off;
                hls_nested on;
            }
        }
    }


annotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "console-ingester"
  vault.hashicorp.com/agent-inject-secret-common: "videocoin/v1/networks/everest-dev/console/common"
  vault.hashicorp.com/agent-inject-secret-config: "videocoin/v1/networks/everest-dev/console/ingester"
  vault.hashicorp.com/agent-inject-template-common: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/common" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
  vault.hashicorp.com/agent-inject-template-config: |
    {{ with secret "videocoin/v1/networks/everest-dev/console/ingester" }}{{ range $k, $v := .Data }}
    export {{ $k }}="{{ $v }}"
    {{ end }}{{ end }}
