replicasCount: 3
maxUnavailableCount: 0

image:
  repository: gcr.io/videocoin-network/ingester
  tag: latest
  pullPolicy: Always

service:
  rtmp:
    type:
    port: 1935
  http:
    type:
    port: 80

resources: {}

hookd:
  image:
    repository: gcr.io/videocoin-network/ingester-hookd
    tag: latest
    pullPolicy: Always
  service:
    http:
      type:
      port: 8887

config:
  fsPath:
  fsAddr:
  rtmpConf: |
    user www-data;

    worker_processes 1;

    events {
        worker_connections 1024;
    }

    rtmp {
        server {
            listen 1935;

            chunk_size 4096;
            max_message 16M;

            application live {
                live on;
                meta copy;

                drop_idle_publisher 10s;

                record_path /data/studio/records;
                record_unique on;

                notify_method         post;
                notify_update_timeout 5s;
                notify_update_strict  on;
                notify_send_redirect  on;
                notify_relay_redirect on;

                on_publish       http://127.0.0.1:8887/hook;
                on_publish_done  http://127.0.0.1:8887/hook;
                on_playlist      http://127.0.0.1:8887/hook;
                on_update        http://127.0.0.1:8887/hook;

                hls on;
                hls_type live;
                hls_fragment 10s;
                hls_playlist_length 43200s;

                hls_fragment_slicing plain;
                hls_path /data/studio/hls;
                hls_cleanup on;
                hls_continuous off;
                hls_nested on;
            }
        }
    }
