swagger: '2.0'
info:
  version: "1.0"
  title: Live Planet Scheduler API
  description: Live Planet Private Transcoder Scheduler API
host: scheduler.cloud.liveplanetstage.net:8010
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /jobs/:
    get:
      summary: Get jobs list
      tags:
        - Jobs
      operationId: GetJobs
      responses:
        "200":
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Job'
    post:
      summary: Create job
      tags:
        - Jobs
      operationId: CreateJob
      responses:
        "201":
          description: success created
          schema:
            type: object
            $ref: '#/definitions/JobDetail'
definitions:
  Job:
    properties:
      id:
        type: string
        description: unique id
    required:
      - id
  JobDetail:
    properties:
      id:
        type: string
        description: unique id